// GENERATED by tools/generate-sw.mjs — do not hand-edit the PRECACHE_URLS
// list, re-run the script instead. Cache-first with network fallback for
// offline navigation; cleans up old caches on activate.
const CACHE_NAME = "elg-7db61df0ae";
const PRECACHE_URLS = [
  "./",
  "content/calculators/calc-blatchford.json",
  "content/calculators/calc-chads.json",
  "content/calculators/calc-curb65.json",
  "content/calculators/calc-gcs.json",
  "content/calculators/calc-heart.json",
  "content/calculators/calc-sodio.json",
  "content/calculators/calc-sofa.json",
  "content/calculators/calc-tac-craneo.json",
  "content/calculators/calc-wells-tep.json",
  "content/calculators/calc-wells-tvp.json",
  "content/drugs/analgesia.json",
  "content/drugs/atb.json",
  "content/drugs/cardio.json",
  "content/drugs/index.json",
  "content/drugs/neuro.json",
  "content/drugs/resp.json",
  "content/home.html",
  "content/meta.json",
  "content/modules/abuso-sexual.html",
  "content/modules/acv.html",
  "content/modules/agitacion.html",
  "content/modules/alt-sensorio.html",
  "content/modules/anafilaxia.html",
  "content/modules/arritmias.html",
  "content/modules/asma.html",
  "content/modules/cad.html",
  "content/modules/calc-nihss.html",
  "content/modules/calc-psi.html",
  "content/modules/cefalea.html",
  "content/modules/celulitis.html",
  "content/modules/colico-biliar.html",
  "content/modules/colico-renal.html",
  "content/modules/convulsiones.html",
  "content/modules/crisis-hta.html",
  "content/modules/delirium.html",
  "content/modules/disnea.html",
  "content/modules/dolor-abdominal.html",
  "content/modules/dolor-toracico.html",
  "content/modules/epoc.html",
  "content/modules/falla-renal.html",
  "content/modules/faringoamig.html",
  "content/modules/fiebre.html",
  "content/modules/gineco-infecciones.html",
  "content/modules/ginecoobs.html",
  "content/modules/hemorragia-digestiva.html",
  "content/modules/hepato-embarazo.html",
  "content/modules/herpes-zoster.html",
  "content/modules/higado-descompensado.html",
  "content/modules/hiperkalemia.html",
  "content/modules/hipoglucemia.html",
  "content/modules/hiponatremia.html",
  "content/modules/hta-gestacional.html",
  "content/modules/ic-aguda.html",
  "content/modules/intoxicaciones.html",
  "content/modules/itu.html",
  "content/modules/lumbalgia.html",
  "content/modules/meningitis.html",
  "content/modules/neumonia.html",
  "content/modules/ojo-rojo.html",
  "content/modules/otitis.html",
  "content/modules/pancreatitis.html",
  "content/modules/panico.html",
  "content/modules/pcr.html",
  "content/modules/politrauma.html",
  "content/modules/rpm-puerperal.html",
  "content/modules/sepsis.html",
  "content/modules/shock.html",
  "content/modules/sincope.html",
  "content/modules/sinusitis.html",
  "content/modules/tec.html",
  "content/modules/tep.html",
  "content/modules/tiroides.html",
  "content/modules/tvp.html",
  "content/modules/vertigo.html",
  "content/rcp/aha-2025-adulto.json",
  "css/components.css",
  "css/layout.css",
  "css/responsive.css",
  "css/tokens.css",
  "icons/apple-touch-icon.png",
  "icons/favicon.svg",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/logo.png",
  "index.html",
  "js/calculators/calc-blatchford.js",
  "js/calculators/calc-chads.js",
  "js/calculators/calc-curb65.js",
  "js/calculators/calc-gcs.js",
  "js/calculators/calc-heart.js",
  "js/calculators/calc-sodio.js",
  "js/calculators/calc-sofa.js",
  "js/calculators/calc-tac-craneo.js",
  "js/calculators/calc-wells-tep.js",
  "js/calculators/calc-wells-tvp.js",
  "js/calculators/engine.js",
  "js/calculators/gestational-age.js",
  "js/calculators/index.js",
  "js/drugs.js",
  "js/legacy-bridge.js",
  "js/main.js",
  "js/rcp/assist.js",
  "js/rcp/constants.js",
  "js/rcp/cues.js",
  "js/rcp/engine.js",
  "js/rcp/note.js",
  "js/rcp/profile.js",
  "js/rcp/settings.js",
  "js/rcp/status.js",
  "js/rcp/storage.js",
  "js/rcp/types.js",
  "js/rcp/ui.js",
  "js/router.js",
  "js/search.js",
  "js/sidebar.js",
  "js/theme.js",
  "manifest.json"
];

self.addEventListener('install', event => {
  event.waitUntil(
    // cache: 'reload' bypasses the browser's HTTP cache (GitHub Pages sends
    // max-age=600), so a fresh deploy is never precached from a stale copy.
    caches.open(CACHE_NAME).then(cache =>
      cache.addAll(PRECACHE_URLS.map(url => new Request(url, { cache: 'reload' })))
    )
  );
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys => {
      // Only this app's caches — the github.io origin is shared with other sites.
      const old = keys.filter(k => k.startsWith('elg-') && k !== CACHE_NAME);
      return Promise.all(old.map(k => caches.delete(k)))
        .then(() => self.clients.claim())
        // On an update (not a first install), pages already open were built
        // with the previous version's CSS/JS; reload them once so they don't
        // render new content against old code.
        .then(() => old.length ? self.clients.matchAll({ type: 'window' }) : [])
        .then(clients => {
          // Not awaited: the reload's own request waits for this activation
          // to finish, so waiting on it here would deadlock.
          clients.forEach(c => c.navigate(c.url).catch(() => {}));
        });
    })
  );
});

self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request).then(cached =>
      cached || fetch(event.request).catch(() => caches.match('./'))
    )
  );
});
