// GENERATED by tools/generate-sw.mjs — do not hand-edit the PRECACHE_URLS
// list, re-run the script instead. Cache-first with network fallback for
// offline navigation; cleans up old caches on activate.
const CACHE_NAME = "elg-v1";
const PRECACHE_URLS = [
  "./",
  "content/calculators/calc-blatchford.json",
  "content/calculators/calc-chads.json",
  "content/calculators/calc-curb65.json",
  "content/calculators/calc-gcs.json",
  "content/calculators/calc-heart.json",
  "content/calculators/calc-sodio.json",
  "content/calculators/calc-sofa.json",
  "content/calculators/calc-wells-tep.json",
  "content/calculators/calc-wells-tvp.json",
  "content/drugs/analgesia.json",
  "content/drugs/atb.json",
  "content/drugs/cardio.json",
  "content/drugs/index.json",
  "content/drugs/neuro.json",
  "content/drugs/resp.json",
  "content/home.html",
  "content/meta.json",
  "content/modules/abuso-sexual.html",
  "content/modules/acv.html",
  "content/modules/agitacion.html",
  "content/modules/alt-sensorio.html",
  "content/modules/anafilaxia.html",
  "content/modules/arritmias.html",
  "content/modules/asma.html",
  "content/modules/cad.html",
  "content/modules/calc-nihss.html",
  "content/modules/calc-psi.html",
  "content/modules/cefalea.html",
  "content/modules/celulitis.html",
  "content/modules/colico-biliar.html",
  "content/modules/colico-renal.html",
  "content/modules/convulsiones.html",
  "content/modules/crisis-hta.html",
  "content/modules/delirium.html",
  "content/modules/disnea.html",
  "content/modules/dolor-abdominal.html",
  "content/modules/dolor-toracico.html",
  "content/modules/epoc.html",
  "content/modules/falla-renal.html",
  "content/modules/faringoamig.html",
  "content/modules/fiebre.html",
  "content/modules/gineco-infecciones.html",
  "content/modules/ginecoobs.html",
  "content/modules/hemorragia-digestiva.html",
  "content/modules/hepato-embarazo.html",
  "content/modules/herpes-zoster.html",
  "content/modules/higado-descompensado.html",
  "content/modules/hiperkalemia.html",
  "content/modules/hipoglucemia.html",
  "content/modules/hiponatremia.html",
  "content/modules/hta-gestacional.html",
  "content/modules/ic-aguda.html",
  "content/modules/intoxicaciones.html",
  "content/modules/itu.html",
  "content/modules/lumbalgia.html",
  "content/modules/meningitis.html",
  "content/modules/neumonia.html",
  "content/modules/ojo-rojo.html",
  "content/modules/otitis.html",
  "content/modules/pancreatitis.html",
  "content/modules/panico.html",
  "content/modules/pcr.html",
  "content/modules/rpm-puerperal.html",
  "content/modules/sepsis.html",
  "content/modules/shock.html",
  "content/modules/sincope.html",
  "content/modules/sinusitis.html",
  "content/modules/tep.html",
  "content/modules/tiroides.html",
  "content/modules/tvp.html",
  "content/modules/vertigo.html",
  "css/components.css",
  "css/layout.css",
  "css/responsive.css",
  "css/tokens.css",
  "icons/apple-touch-icon.png",
  "icons/favicon.svg",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/logo.png",
  "index.html",
  "js/calculators/calc-blatchford.js",
  "js/calculators/calc-chads.js",
  "js/calculators/calc-curb65.js",
  "js/calculators/calc-gcs.js",
  "js/calculators/calc-heart.js",
  "js/calculators/calc-sodio.js",
  "js/calculators/calc-sofa.js",
  "js/calculators/calc-wells-tep.js",
  "js/calculators/calc-wells-tvp.js",
  "js/calculators/engine.js",
  "js/calculators/gestational-age.js",
  "js/calculators/index.js",
  "js/drugs.js",
  "js/legacy-bridge.js",
  "js/main.js",
  "js/router.js",
  "js/search.js",
  "js/sidebar.js",
  "js/theme.js",
  "manifest.json"
];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(PRECACHE_URLS))
  );
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request).then(cached =>
      cached || fetch(event.request).catch(() => caches.match('./'))
    )
  );
});
