// Dev-only generator (not a build step — its output, sw.js, is a plain
// committed file the browser fetches directly, same as any other asset).
// Re-run this manually whenever files are added/removed/renamed under
// css/, js/, content/, or icons/, then commit the updated sw.js.
//   node tools/generate-sw.mjs [cacheVersion]
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const root = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const INCLUDE_DIRS = ['css', 'js', 'content', 'icons'];
const INCLUDE_FILES = ['index.html', 'manifest.json'];

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

let files = [...INCLUDE_FILES];
for (const dir of INCLUDE_DIRS) {
  files.push(...walk(join(root, dir)).map(f => relative(root, f)));
}
files = files.map(f => f.split(sep).join('/')).sort();

const version = process.argv[2] || new Date().toISOString().slice(0, 10);
const cacheName = `elg-v${version}`;

const urls = ['./', ...files];

const swSource = `// GENERATED by tools/generate-sw.mjs — do not hand-edit the PRECACHE_URLS
// list, re-run the script instead. Cache-first with network fallback for
// offline navigation; cleans up old caches on activate.
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE_URLS = ${JSON.stringify(urls, null, 2)};

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(PRECACHE_URLS))
  );
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request).then(cached =>
      cached || fetch(event.request).catch(() => caches.match('./'))
    )
  );
});
`;

writeFileSync(join(root, 'sw.js'), swSource);
console.log(`Wrote sw.js — ${urls.length} URLs precached, cache name ${cacheName}`);
